version: 2

jobs:
  linux:
    docker:
      - image: vapor/swift:5.0
      - image: vimagick/tinyproxy
        name: tinyproxy
    steps:
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
